// tailwind-admin-vuejs-free/package/src/components/shared/CardBox.vue
<template>
  <Card :class="[
    'card no-inset no-ring shadow-none border border-ld rounded-lg w-full',
    customClass
  ]">
    <slot />
  </Card>
</template>

<script lang="ts" setup>
import {Card} from '@/components/ui/card'; 



const props = defineProps({
  class: String,
});

const customClass = props.class || '';
</script>

// tailwind-admin-tanstack-start/package/src/components/shared/CardBox.tsx
import React from "react";
import { Card } from "../ui/card";

interface MyAppProps {
  children: React.ReactNode;
  className?: string;
}
const CardBox: React.FC<MyAppProps> = ({ children, className }) => {
  return (
    <Card
      className={`card no-inset no-ring ${className} shadow-none border border-ld rounded-lg w-full`}
    >
      {children}
    </Card>
  );
};
export default CardBox;
