// tailwind-admin-tanstack-start/package/src/components/authentication/auth2/Login.tsx
import { Link } from "@tanstack/react-router";
import CardBox from "src/components/shared/CardBox";

import AuthLogin from "../authforms/AuthLogin";
import SocialButtons from "../authforms/SocialButtons";

import FullLogo from "src/layouts/full/shared/logo/FullLogo";


const Login = () => {
  return (
    <>
      <div className="relative overflow-hidden h-screen bg-lightprimary dark:bg-darkprimary">
        <div className="flex h-full justify-center items-center px-4">
          <CardBox className="md:w-[450px] w-full border-none">
            <div className="mx-auto mb-6">
              <FullLogo />
            </div>
            <SocialButtons title="or sign in with" />
            <AuthLogin />
            <div className="flex gap-2 text-base text-ld font-medium mt-6 items-center justify-center">
              <p>New to TailwindAdmin?</p>
              <Link
                to={"/auth/register"}
                className="text-primary text-sm font-medium"
              >
                Create an account
              </Link>
            </div>
          </CardBox>
        </div>
      </div>
    </>
  );
};

export default Login;

// tailwind-admin-vuejs-free/package/src/views/authentication/auth2/Login.vue
<script setup lang="tsx">
import { RouterLink } from 'vue-router'
import FullLogo from '@/layouts/full/logo/Logo.vue'
import AuthLogin from '@/views/authentication/authforms/AuthLogin.vue'
import SocialButtons from '@/views/authentication/authforms/SocialButtons.vue'
import Card from '@/components/ui/card/Card.vue'
</script>



<template>
  <div class="relative overflow-hidden h-screen bg-lightprimary dark:bg-darkprimary">
    <div class="flex h-full justify-center items-center px-4">
      <Card class="md:w-[450px] w-full border-none gap-0">
        <div class=" flex items-center justify-center">
          <FullLogo />
        </div>
        <SocialButtons title="or sign in with" />
        <AuthLogin />
        <div class="flex gap-2 text-base text-ld font-medium mt-6 items-center justify-center">
          <p>New to TailwindAdmin?</p>
          <RouterLink to="/auth/register2" class="text-primary text-sm font-medium">
            Create an account
          </RouterLink>
        </div>
      </Card>
    </div>
  </div>

</template>
