// tailwind-admin-vuejs-free/package/src/views/authentication/authforms/AuthLogin.vue
<script setup>
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
import Button from '@/components/ui/button/Button.vue'

import Checkbox from '@/components/ui/checkbox/Checkbox.vue'
import Label from '@/components/ui/label/Label.vue'
import { Input } from '@/components/ui/input'


const username = ref('')
const password = ref('')
const rememberDevice = ref(false)

function onSubmit(event) {
  event.preventDefault()

  console.log('Login:', { username: username.value, password: password.value, rememberDevice: rememberDevice.value })
}
</script>

<template>
  <form @submit="onSubmit" class="mt-6">
    <div class="mb-4">
      <div className="mb-2 block">
        <Label for="Username">Username</Label>
      </div>
      <Input id="username" v-model="username" class="form-control" />
    </div>

    <div class="mb-4">
      <div className="mb-2 block">
        <Label for="userpwd">Password</Label>
      </div>
      <Input id="userpwd" type="password" v-model="password" class="form-control" />
    </div>

    <div class="flex justify-between my-5 items-center">
      <div class="flex items-center gap-2">
        <Checkbox id="accept" v-model="rememberDevice" class="checkbox" />
        <Label for="accept" class="opacity-90 font-normal cursor-pointer">
          Remeber this Device
        </Label>
      </div>
      <RouterLink to="#" class="text-primary text-sm font-medium">
        Forgot Password?
      </RouterLink>
    </div>
    <Button class="w-full">
      <RouterLink to="/"> Sign in</RouterLink>
    </Button>
  </form>
</template>

// tailwind-admin-tanstack-start/package/src/components/authentication/authforms/AuthLogin.tsx
import { Link } from '@tanstack/react-router';
import { Button } from 'src/components/ui/button';
import { Checkbox } from 'src/components/ui/checkbox';
import { Input } from 'src/components/ui/input';
import { Label } from 'src/components/ui/label';

const AuthLogin = () => {
  return (
    <>
      <form className="mt-6">
        <div className="mb-4">
          <div className="mb-2 block">
            <Label htmlFor="Username">Username</Label>
          </div>
          <Input id="username" type="text" />
        </div>
        <div className="mb-4">
          <div className="mb-2 block">
            <Label htmlFor="userpwd">Password</Label>
          </div>
          <Input id="userpwd" type="password" />
        </div>
        <div className="flex justify-between my-5">
          <div className="flex items-center gap-2">
            <Checkbox id="accept" className="checkbox" />
            <Label htmlFor="accept" className="opacity-90 font-normal cursor-pointer">
              Remeber this Device
            </Label>
          </div>
          <Link to={'/'} className="text-primary text-sm font-medium">
            Forgot Password ?
          </Link>
        </div>
        <Button asChild className="w-full">
          <Link to="/">Sign in</Link>
        </Button>
      </form>
    </>
  );
};

export default AuthLogin;
