// tailwind-admin-reactjs-free/package/src/components/dashboards/modern/RecentTransaction.tsx
import CardBox from 'src/components/shared/CardBox';

export const RecentTransaction = () => {
  const timelineData = [
    {
      key: 'timeline1',
      time: '09:30 am',
      desc: 'Payment received from John Doe of $385.90',
      isSale: false,
      borderColor: 'border-primary',
      isLastItem: false,
    },
    {
      key: 'timeline2',
      time: '10:00 am',
      desc: 'New sale recorded',
      isSale: true,
      borderColor: 'border-info',
      isLastItem: false,
    },
    {
      key: 'timeline3',
      time: '12:00 am',
      desc: 'Payment was made of $64.95 to Michael',
      isSale: false,
      borderColor: 'border-success',
      isLastItem: false,
    },
    {
      key: 'timeline4',
      time: '09:30 am',
      desc: 'New sale recorded',
      isSale: true,
      borderColor: 'border-warning',
      isLastItem: false,
    },
    {
      key: 'timeline5',
      time: '09:30 am',
      desc: 'New sale recorded',
      isSale: true,
      borderColor: 'border-error',
      isLastItem: false,
    },
    {
      key: 'timeline6',
      time: '12:00 am',
      desc: 'Payment Done',
      isSale: false,
      borderColor: 'border-success',
      isLastItem: true,
    },
  ];
  return (
    <CardBox className="h-full w-full ">
      <div>
        <h5 className="card-title">Recent Transactions</h5>
        <p className="text-sm text-muted-foreground font-normal">
          How to secure recent transactions
        </p>
      </div>

      <div className="mt-6">
        {timelineData.map((item) => {
          return (
            <div key={item.key} className="flex gap-x-3">
              <div className="w-1/4 text-end">
                <span className="font-medium text-foreground dark:text-muted-foreground">{item.time}</span>
              </div>
              <div
                className={`relative ${
                  item.isLastItem ? 'after:hidden' : null
                } after:absolute after:top-7 after:bottom-0 after:start-3.5 after:w-px after:-translate-x-[0.5px] after:bg-border`}
              >
                <div className="relative z-1 w-7 h-7 flex justify-center items-center">
                  <div
                    className={`h-3 w-3 rounded-full bg-transparent border-2 ${item.borderColor}`}
                  ></div>
                </div>
              </div>
              <div className="w-1/4 grow pt-0.5 pb-6">
                {!item.isSale ? (
                  <p className="font-medium text-foreground dark:text-muted-foreground">{item.desc}</p>
                ) : (
                  <div>
                    <h6>New sale recorded </h6>
                    <span className="text-primary">#ML-3467</span>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </CardBox>
  );
};

// tailwind-admin-vuejs-free/package/src/components/dashboards/modern/RecentTransaction.vue
<script lang="ts" setup>
import { Card } from '@/components/ui/card/index'
import { RecentTransaction } from '@/_mockApis/dashboardData/modernData'



</script>

<template>
  <Card class="h-full">
    <div class="flex flex-col gap-1.5">
      <h5 class="card-title">Recent Transactions</h5>
      <p class="card-subtitle">How to secure recent transactions</p>
    </div>

    <div class="mt-6">
      <div class="flex flex-col gap-6">
        <div v-for="(item, index) in RecentTransaction" :key="item.key" :index="index">
          <div class="flex gap-x-3">
            <div class="w-1/4 text-end">
              <span>{{ item.time }}</span>
            </div>

            <div :class="[
              'relative',
              item.isLastItem ? 'after:hidden' : '',
              'after:absolute after:top-7 after:bottom-0 after:start-3.5 after:w-px after:-translate-x-[0.5px] after:bg-border after:h-9 dark:after:bg-darkborder',
            ]">
              <div class="relative z-1 w-7 h-7 flex justify-center items-center">
                <div :class="[
                  'h-3 w-3 rounded-full bg-transparent border-2',
                  item.borderColor,
                ]"></div>
              </div>
            </div>

            <div class="w-1/4 grow">
              <template v-if="!item.isSale">
                <p>{{ item.desc }}</p>
              </template>
              <template v-else>
                <div>
                  <h6>New sale recorded</h6>
                  <RouterLink to="#" class="text-primary">#ML-3467</RouterLink>
                </div>
              </template>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Card>
</template>
