// tailwind-admin-vuejs-free/package/src/layouts/full/FullLayout.vue
<script setup lang="ts">
import { SidebarProvider } from "@/components/ui/sidebar";
import LayoutVerticalSidebar from "./vertical-sidebar/VerticalSidebar.vue";
import LayoutVerticalHeader from "./vertical-header/VerticalHeader.vue";

</script>

<template>

  <SidebarProvider>
    <div class="flex w-full min-h-screen">

      <div class="flex ">
        <LayoutVerticalSidebar />
      </div>


      <!-- Main content wrapper -->
      <div class=" w-full  bg-white dark:bg-dark">
        <LayoutVerticalHeader />
        <!-- Page content -->
        <main class="flex-grow">
          <div class="
              container mx-auto py-[30px] px-6
          ">
            <RouterView />
          </div>
        </main>
      </div>
    </div>
  </SidebarProvider>

</template>

// tailwind-admin-tanstack-start/package/src/layouts/full/FullLayout.tsx
import { FC, ReactNode } from "react";
import Sidebar from "./vertical/sidebar/Sidebar";
import Header from "./vertical/header/Header";

const FullLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <>
      <div className="flex w-full min-h-screen">
        <div className="page-wrapper flex w-full ">
          {/* Header/sidebar */}
          <div className="xl:block hidden">
            <Sidebar />
          </div>
          <div className="body-wrapper w-full bg-white dark:bg-dark">
            {/* Top Header  */}
            <Header />

            {/* Body Content  */}
            <div className={'container mx-auto px-6 py-30'}>
              <main className="grow">
                {children}
              </main>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};




export default FullLayout;
