// tailwind-admin-vuejs-free/package/src/components/dashboards/modern/YearlyBreakup.vue
<script setup lang="ts">
import { ref } from 'vue'
import VueApexCharts from 'vue3-apexcharts'
import { Icon } from '@iconify/vue'

import Card from '@/components/ui/card/Card.vue'

// The data structure, same as React version
const chartOptions: any = ref({
  chart: {
    type: 'donut',
    fontFamily: 'inherit',
    foreColor: '#adb0bb',
    height: 155,
    offsetX: 18,
    toolbar: {
      show: false,
    },
  },
  plotOptions: {
    pie: {
      startAngle: 0,
      endAngle: 360,
      donut: {
        size: '75%',
      },
    },
  },
  stroke: {
    show: false,
  },
  dataLabels: {
    enabled: false,
  },
  legend: {
    show: false,
  },
  colors: [
    'var(--color-primary)',
    'var(--color-lightprimary)',
    'var(--color-secondary)',
  ],
  tooltip: {
    theme: 'dark',
    fillSeriesColor: false,
    y: {
      formatter: (value: number) => {
        return `$${value.toLocaleString()}K`
      },
    },
  },

})

const series = ref([38, 40, 25])
</script>

<template>
  <Card class="h-full">
    <div class="grid grid-cols-12 ">
      <!-- Left portion -->
      <div class="lg:col-span-6 md:col-span-6 col-span-8">
        <h5 class="card-title mb-4 lg:whitespace-nowrap">Yearly Breakup</h5>
        <h4 class="text-xl mb-3">
          $36358


        </h4>
        <div class="flex items-center mb-3 gap-2">
          <span class="rounded-full p-1 bg-lightsuccess dark:bg-darksuccess flex items-center justify-center">
            <Icon icon="tabler:arrow-up-left" class="text-success" />
          </span>
          <p class="text-dark dark:text-darklink mb-0">+9%</p>
          <p class="dark:text-darklink mb-0">last year</p>
        </div>
        <div class="flex gap-4 items-center mt-4">
          <div class="flex items-center">
            <Icon icon="tabler:point-filled" class="text-primary text-xl me-1" />
            <span class="text-xs dark:text-darklink">2023</span>
          </div>
          <div class="flex items-center">
            <Icon icon="tabler:point-filled" class="text-secondary text-xl me-1" />
            <span class="text-xs dark:text-darklink">2024</span>
          </div>
          <div class="flex items-center">
            <Icon icon="tabler:point-filled" class="text-lightprimary text-xl me-1" />
            <span class="text-xs dark:text-darklink">2025</span>
          </div>
        </div>
      </div>






      <div class="lg:col-span-6 md:col-span-6 col-span-4">
        <div class="w-full max-w-[300px]">
          <VueApexCharts :options="chartOptions" :series="series" type="donut" />
        </div>
      </div>


    </div>
  </Card>
</template>

// tailwind-admin-reactjs-free/package/src/components/dashboards/modern/YearlyBreakup.tsx
import { Icon } from "@iconify/react/dist/iconify.js";
import CardBox from "src/components/shared/CardBox";
import Chart from 'react-apexcharts';
import { ApexOptions } from "apexcharts";

const YearlyBreakup = () => {

    const ChartData: ApexOptions = {
        series: [
            38, 40, 25
        ],
        labels: ["2023", "2025", "2024"],
        chart: {
            type: "donut",
            fontFamily: "inherit",
            foreColor: "#adb0bb",
            height: 150,
            offsetX: 18,
            toolbar: {
                show: false,
            },
        },
        plotOptions: {
            pie: {
                startAngle: 0,
                endAngle: 360,
                donut: {
                    size: '75%',
                },
            },
        },
        stroke: {
            show: false,
        },

        dataLabels: {
            enabled: false,
        },

        legend: {
            show: false,
        },
        colors: ["var(--color-primary)", "var(--color-lightprimary)", "var(--color-secondary)"],


        tooltip: {
            theme: "dark",
            fillSeriesColor: false,
            y: {
                formatter: (val: number) => {
                    return `$${val}K`;
                }
            }
        },
    };
    return (
        <>
            <CardBox>
                <div className="grid grid-cols-12 ">
                    <div className="flex flex-col lg:col-span-6 md:col-span-6 col-span-7">
                        <div>
                            <h5 className="card-title mb-4 lg:whitespace-nowrap">Yearly Breakup</h5>
                            <h4 className="text-xl mb-2">$36,358</h4>
                            <div className="flex items-center mb-3 gap-2">
                                <span className="rounded-full p-1 bg-lightsuccess dark:bg-darksuccess flex items-center justify-center ">
                                    <Icon icon="tabler:arrow-up-left" className="text-success" />
                                </span>
                                <p className="text-muted-foreground mb-0">+9%</p>
                                <p className="text-muted-foreground mb-0 ">last year</p>
                            </div>
                        </div>
                        <div className="flex flex-wrap gap-4 items-center mt-4">
                            <div className="flex items-center">
                                <Icon icon="tabler:point-filled" className="text-primary text-xl me-1" />
                                <span className="text-xs text-muted-foreground">2023</span>
                            </div>
                            <div className="flex items-center">
                                <Icon icon="tabler:point-filled" className="text-secondary text-xl me-1" />
                                <span className="text-xs text-muted-foreground">2024</span>
                            </div>
                            <div className="flex items-center">
                                <Icon icon="tabler:point-filled" className="text-lightprimary text-xl me-1" />
                                <span className="text-xs text-muted-foreground">2025</span>
                            </div>
                        </div>
                    </div>
                    <div className="lg:col-span-6 md:col-span-6 col-span-4">
                        <div className="flex justify-center">
                            <Chart
                                options={ChartData}
                                series={ChartData.series}
                                type="donut"
                                height={150}
                                width={180}
                            />
                        </div>
                    </div>
                </div>

            </CardBox>
        </>
    )
}
export { YearlyBreakup }
